# Set the build language to Python
language: python

# Set the python version
python:
  - "3.8"
  - "3.9"

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - python -m pytest --cov=stock_pairs_trading tests/

# Push the results back to codecov
after_success:
  - codecov
